# coding: utf-8
#
require 'spec_helper'

# Auto-generated by build_w3c_tests.rb
#
# graph-09
# Data: default and named / Query: named graph
# /Users/ben/repos/datagraph/tests/tests/data-r2/graph/graph-09.rq
#
# This is a W3C test from the DAWG test suite:
# http://www.w3.org/2001/sw/DataAccess/tests/r2#dawg-graph-09
#
# This test is approved: 
# http://lists.w3.org/Archives/Public/public-rdf-dawg/2007JulSep/att-0047/31-dawg-minutes
#
# 20101218 jaa bug indicator as graphs are NYI

describe "W3C test" do
  context "graph" do
    before :all do
      @g3 = %q{
        @prefix : <http://example/> .
        @prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .

        _:x :p "1"^^xsd:integer .
        _:a :p "9"^^xsd:integer .
      }
      @g4 = %q{
        @prefix : <http://example/> .
        @prefix xsd:        <http://www.w3.org/2001/XMLSchema#> .

        _:x :q "2"^^xsd:integer .
     }
      @query = %q{
        (prefix ((: <http://example/>))
          (join
            (bgp (triple ?s ?p ?o))
            (graph ?g
              (bgp (triple ?s ?q ?v)))))
      }
    end

    example "graph-09", :status => 'bug' do
    
      graphs = {}
      graphs[:default] = { :data => @g3, :format => :ttl}

      graphs[RDF::URI('data-g4.ttl')] = { :data => @g4, :format => :ttl }

      repository = 'graph-dawg-graph-09'
      expected = [
      ]


      sparql_query(:graphs => graphs, :query => @query,       # unordered comparison in rspec is =~
                   :repository => repository, :form => :select).should =~ expected
    end
  end
end
